/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddressFind: typeof import('./src/components/etc/AddressFind.vue')['default']
    ComButton: typeof import('./src/components/form/ComButton.vue')['default']
    ComCheckbox: typeof import('./src/components/form/ComCheckbox.vue')['default']
    ComInput: typeof import('./src/components/form/ComInput.vue')['default']
    Dashboard_01: typeof import('./src/components/main/layout/dashboard/Dashboard_01.vue')['default']
    Dashboard_02: typeof import('./src/components/main/layout/dashboard/Dashboard_02.vue')['default']
    EmailAddress: typeof import('./src/components/etc/EmailAddress.vue')['default']
    HomeView: typeof import('./src/components/main/layout/HomeView.vue')['default']
    Login: typeof import('./src/components/mobile/login.vue')['default']
    LoginPage: typeof import('./src/components/login/LoginPage.vue')['default']
    MainFooter: typeof import('./src/components/main/layout/MainFooter.vue')['default']
    MainHeader: typeof import('./src/components/main/layout/MainHeader.vue')['default']
    MainLeft: typeof import('./src/components/main/layout/MainLeft.vue')['default']
    MainLoading: typeof import('./src/components/main/MainLoading.vue')['default']
    MainPage: typeof import('./src/components/main/MainPage.vue')['default']
    MainTab: typeof import('./src/components/main/layout/MainTab.vue')['default']
    MenuContent: typeof import('./src/components/menu/MenuContent.vue')['default']
    MenuTop: typeof import('./src/components/menu/MenuTop.vue')['default']
    MobileMain: typeof import('./src/components/mobile/mobileMain.vue')['default']
    MobileMenu: typeof import('./src/components/mobile/mobileMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UI_MOB_002: typeof import('./src/components/mobile/UI_MOB_002.vue')['default']
    UI_MOB_002P01: typeof import('./src/components/mobile/UI_MOB_002P01.vue')['default']
    UI_MOB_003: typeof import('./src/components/mobile/UI_MOB_003.vue')['default']
    UI_MOB_003P01: typeof import('./src/components/mobile/UI_MOB_003P01.vue')['default']
    UI_MOB_004: typeof import('./src/components/mobile/UI_MOB_004.vue')['default']
    UI_MOB_004P01: typeof import('./src/components/mobile/UI_MOB_004P01.vue')['default']
    UI_MOB_005: typeof import('./src/components/mobile/UI_MOB_005.vue')['default']
    UI_MOB_005P01: typeof import('./src/components/mobile/UI_MOB_005P01.vue')['default']
    UI_MOB_005P02: typeof import('./src/components/mobile/UI_MOB_005P02.vue')['default']
    UI_MOB_P01: typeof import('./src/components/mobile/UI_MOB_P01.vue')['default']
    UI_MOB_P02: typeof import('./src/components/mobile/UI_MOB_P02.vue')['default']
    UI_USR_P02: typeof import('./src/components/popup/UI_USR_P02.vue')['default']
    UI_USR_P03: typeof import('./src/components/popup/UI_USR_P03.vue')['default']
  }
}
